######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 17 17:44:25 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lexer.h
SOURCES += lexer.cpp main.cpp
